name: Build Test

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
      - run: yarn install --prefer-offline
      - run: yarn build
      - run: yarn lint
